#!/usr/bin/env node

var fs = require('fs');
var exec = require('child_process').exec;

var package_json = JSON.parse(fs.readFileSync('package.json', 'utf8'));
var bower_json = fs.readFileSync('bower.json', 'utf8');

new_bower_json = bower_json.replace(/"version": .+/, "\"version\": \"" + package_json.version + "\",");

fs.writeFileSync('bower.json', new_bower_json);
